from __future__ import annotations

import json
import inspect
from typing import List

from ..brain.gemini import GeminiBrain
from ..brain.openai_compat import OpenAICompatBrain
from ..models import AppConfig
from ..skills.registry import SkillRegistry
from .missions import MissionStep, MissionTemplate


class MissionPlannerError(RuntimeError):
    pass


def _expected_args_for_skill(registry: SkillRegistry, skill_id: str) -> List[str]:
    """Return keyword-compatible argument names for the skill entrypoint."""
    manifest = registry.get(skill_id)
    fn = registry.load_entrypoint(manifest)
    sig = inspect.signature(fn)
    names: List[str] = []
    for p in sig.parameters.values():
        if p.kind in (inspect.Parameter.POSITIONAL_OR_KEYWORD, inspect.Parameter.KEYWORD_ONLY):
            names.append(p.name)
    return names


def _normalize_step_args(raw_args: object, expected_args: List[str]) -> dict:
    if not isinstance(raw_args, dict):
        return {}

    if not expected_args:
        return raw_args

    normalized = {k: v for k, v in raw_args.items() if k in expected_args}
    if normalized:
        return normalized

    # Compatibility fallback: if the planner picked the wrong key for a
    # single-argument skill (e.g. app_name vs name), map the single provided
    # value to the expected parameter.
    if len(expected_args) == 1 and len(raw_args) == 1:
        return {expected_args[0]: next(iter(raw_args.values()))}

    return {}


def _build_brain(cfg: AppConfig):
    if not cfg.privacy.cloud_allowed:
        raise MissionPlannerError("Cloud planning is disabled by privacy.cloud_allowed=false")

    primary = cfg.brain.get("primary")
    if not primary and cfg.brain:
        primary = next(iter(cfg.brain.values()))

    if not primary:
        raise MissionPlannerError("No brain provider is configured. Run 'voxera setup' first.")

    if primary.type == "openai_compat":
        return OpenAICompatBrain(
            base_url=primary.base_url or "",
            model=primary.model,
            api_key_ref=primary.api_key_ref,
            extra_headers=primary.extra_headers,
        )

    if primary.type == "gemini":
        return GeminiBrain(model=primary.model, api_key_ref=primary.api_key_ref)

    raise MissionPlannerError(f"Unsupported brain provider for mission planning: {primary.type}")


async def plan_mission(goal: str, cfg: AppConfig, registry: SkillRegistry) -> MissionTemplate:
    brain = _build_brain(cfg)
    skills = sorted(registry.discover().values(), key=lambda m: m.id)

    skills_block = "\n".join(
        f"- {m.id}: {m.description} (risk={m.risk}, caps={','.join(m.capabilities) or 'none'})"
        for m in skills
    )

    messages = [
        {
            "role": "system",
            "content": (
                "You are a strict mission planner for Voxera OS. "
                "Output JSON only with keys: title, goal, notes, steps. "
                "steps must be 1-5 items and each item has skill_id and args object. "
                "Use only skill IDs from the provided catalog."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Goal: {goal}\n"
                f"Skill catalog:\n{skills_block}\n"
                "Return only JSON."
            ),
        },
    ]

    resp = await brain.generate(messages)
    raw = resp.text.strip()

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise MissionPlannerError(f"Planner returned non-JSON output: {raw[:200]}") from exc

    steps_json: List[dict] = payload.get("steps") or []
    if not steps_json:
        raise MissionPlannerError("Planner returned no mission steps.")

    known_ids = {m.id for m in skills}
    steps: List[MissionStep] = []
    for item in steps_json[:5]:
        skill_id = item.get("skill_id")
        if skill_id not in known_ids:
            raise MissionPlannerError(f"Planner referenced unknown skill: {skill_id}")
        args = _normalize_step_args(item.get("args"), _expected_args_for_skill(registry, skill_id))
        steps.append(MissionStep(skill_id=skill_id, args=args))

    title = payload.get("title") or "Cloud Planned Mission"
    notes = payload.get("notes") or "Generated by configured cloud brain."

    return MissionTemplate(id="cloud_planned", title=title, goal=goal, steps=steps, notes=notes)
