from __future__ import annotations

import json
from typing import List

from ..brain.gemini import GeminiBrain
from ..brain.openai_compat import OpenAICompatBrain
from ..models import AppConfig
from ..skills.registry import SkillRegistry
from .missions import MissionStep, MissionTemplate


class MissionPlannerError(RuntimeError):
    pass


def _build_brain(cfg: AppConfig):
    if not cfg.privacy.cloud_allowed:
        raise MissionPlannerError("Cloud planning is disabled by privacy.cloud_allowed=false")

    primary = cfg.brain.get("primary")
    if not primary and cfg.brain:
        primary = next(iter(cfg.brain.values()))

    if not primary:
        raise MissionPlannerError("No brain provider is configured. Run 'voxera setup' first.")

    if primary.type == "openai_compat":
        return OpenAICompatBrain(
            base_url=primary.base_url or "",
            model=primary.model,
            api_key_ref=primary.api_key_ref,
            extra_headers=primary.extra_headers,
        )

    if primary.type == "gemini":
        return GeminiBrain(model=primary.model, api_key_ref=primary.api_key_ref)

    raise MissionPlannerError(f"Unsupported brain provider for mission planning: {primary.type}")


async def plan_mission(goal: str, cfg: AppConfig, registry: SkillRegistry) -> MissionTemplate:
    brain = _build_brain(cfg)
    skills = sorted(registry.discover().values(), key=lambda m: m.id)

    skills_block = "\n".join(
        f"- {m.id}: {m.description} (risk={m.risk}, caps={','.join(m.capabilities) or 'none'})"
        for m in skills
    )

    messages = [
        {
            "role": "system",
            "content": (
                "You are a strict mission planner for Voxera OS. "
                "Output JSON only with keys: title, goal, notes, steps. "
                "steps must be 1-5 items and each item has skill_id and args object. "
                "Use only skill IDs from the provided catalog."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Goal: {goal}\n"
                f"Skill catalog:\n{skills_block}\n"
                "Return only JSON."
            ),
        },
    ]

    resp = await brain.generate(messages)
    raw = resp.text.strip()

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise MissionPlannerError(f"Planner returned non-JSON output: {raw[:200]}") from exc

    steps_json: List[dict] = payload.get("steps") or []
    if not steps_json:
        raise MissionPlannerError("Planner returned no mission steps.")

    known_ids = {m.id for m in skills}
    steps: List[MissionStep] = []
    for item in steps_json[:5]:
        skill_id = item.get("skill_id")
        if skill_id not in known_ids:
            raise MissionPlannerError(f"Planner referenced unknown skill: {skill_id}")
        args = item.get("args")
        if not isinstance(args, dict):
            args = {}
        steps.append(MissionStep(skill_id=skill_id, args=args))

    title = payload.get("title") or "Cloud Planned Mission"
    notes = payload.get("notes") or "Generated by configured cloud brain."

    return MissionTemplate(id="cloud_planned", title=title, goal=goal, steps=steps, notes=notes)
